// <auto-generated />
namespace MiTienda.Ingraestructura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EntidadesPrimerIteraccion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntidadesPrimerIteraccion));
        
        string IMigrationMetadata.Id
        {
            get { return "202109022252028_Entidades Primer Iteraccion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
